/* JOINS - TIPOS DE JUNÇÕES SIMPLES
sintaxe
SELECT COLUNA
FROM TABELA1 - ESQUERDA
INNER JOIN TABELA2(DIREITA)
  ON(JUNÇÃO) TABELA1.COLUNA = TABELA2.COLUNA
WHERE CONDIÇÃO
*/


--CONSULTA QUE APRESENTE O NOME DE CADA REGIONAL E SEUS  RESPETIVOS VENDEDORES
SELECT TB_REGIONAL.NOME , TB_VENDEDORES.NOME -- SELECIONANDO COLUNAS DAS TABELAS
FROM TB_REGIONAL --- TABELA DA ESQUERDA
 INNER JOIN
 TB_VENDEDORES ---TABELA DA DIREITA
 ON TB_REGIONAL.IDREGIONAL = TB_VENDEDORES.IDREGIONAL --(JUNÇÃO DAS TABELAS)

------------------------------------------------------------------------------
--APELIDO EM TABELA NO JOIN

SELECT r.nome AS regional_nome, v.nome AS vendedor_nome
FROM TB_REGIONAL r
INNER JOIN TB_VENDEDORES v ON r.idregional = v.idregional;

--- CONSULTA QUE APRESENTE A LISTA DE CLIENTES E A QUANTIDADE TOTAL DE PEDIDOS
--FEITOS , SEM RESTRIÇÃO DE TEMPO

SELECT C.NOME,
 COUNT(P.IDPEDIDO) AS QTDPEDIDOS
	FROM TB_CLIENTE C
	INNER JOIN 
	TB_PEDIDOS P
	ON C.IDCLIENTE = P.IDCLIENTE
	GROUP BY 
	C.NOME

---SELECIONA : NOME DO CLIENTE E A MÉDIA DO VALOR DOS PEDIDOS
SELECT C.NOME,
AVG(P.VALORTOTAL) AS MEDIATOTAL
  FROM TB_CLIENTE C
INNER JOIN
TB_PEDIDOS P ON C.IDCLIENTE = P.IDCLIENTE
GROUP BY C.NOME


--EXECUTE A CONSULTA AGORA ALTERANDO A CLAUSULA INNER JOIN E LEFT JOIN

SELECT r.nome AS regional_nome, v.nome AS vendedor_nome
FROM TB_REGIONAL r
LEFT JOIN TB_VENDEDORES v ON r.idregional = v.idregional;

--EXECUTE A CONSULTA AGORA ALTERANDO A CLAUSULA  LEFT JOIN PARA RIGHT JOIN

SELECT r.nome AS regional_nome, v.nome AS vendedor_nome
FROM TB_REGIONAL r
RIGHT JOIN TB_VENDEDORES v ON r.idregional = v.idregional;

-- Listar todos os pedidos e os nomes dos clientes que os realizaram.
--PEDIDOS - COLUNA IDPEDIDO , DATAPEDIDO , VALORTOTAL
--CLIENTE NOME E CPF -- JUNÇÃO COM INNER JOIN
 SELECT
 P.IDPEDIDO,
 P.DATAPEDIDO,
 P.VALORTOTAL,
 C.NOME ,
 C.CPF

 FROM TB_PEDIDOS AS P
  INNER JOIN TB_CLIENTE AS C ON P.IDCLIENTE =  C.IDCLIENTE


--INNER JOIN em múltiplas tabelas
-- Listar os pedidos, 
--o nome do cliente e o nome do vendedor associado a cada um.
SELECT 
P.IDPEDIDO,
P.DATAPEDIDO,
C.NOME AS CLIENTE,
V.NOME AS VENDEDOR

FROM TB_PEDIDOS AS P
INNER JOIN TB_CLIENTE AS C ON  P.IDCLIENTE = C.IDCLIENTE

INNER JOIN TB_VENDEDORES AS V ON P.IDVENDEDOR = V.IDVENDEDOR


-- Combinação de JOINs com WHERE
-- Listar os nomes de clientes, vendedores e os valores totais dos pedidos
-- feitos na Regional  'Rio de Janeiro'.

SELECT
C.NOME AS CLIENTE,
V.NOME AS VENDEDOR,
P.VALORTOTAL,
R.NOME AS REGIONAL

FROM TB_PEDIDOS AS P
INNER JOIN TB_CLIENTE AS C ON P.IDCLIENTE = C.IDCLIENTE
INNER JOIN TB_VENDEDORES AS V ON P.IDVENDEDOR = V.IDVENDEDOR
INNER JOIN TB_REGIONAL AS R ON C.IDREGIONAL = R.IDREGIONAL
WHERE R.NOME = 'Regional Rio de Janeiro'


--Este exemplo junta as tabelas `TB_PEDIDOS` e `ITENSPEDIDO` para calcular a soma
-- da quantidade de itens multiplicada pelo preço unitário, agrupado por pedido.
SELECT
P.IDPEDIDO,
P.DATAPEDIDO,

SUM(IP.QUANTIDADE * IP.PRECOUNITARIO) AS VALORITENS,
P.VALORTOTAL
FROM TB_PEDIDOS AS P

INNER JOIN ITENSPEDIDO AS IP  ON P.IDPEDIDO = IP.IDPEDIDO
GROUP BY P.IDPEDIDO , P.DATAPEDIDO, P.VALORTOTAL


--Juntamos a tabela `TB_PRODUTOS` com `ITENSPEDIDO` para ver quantos de cada
-- produto foram vendidos, usando `SUM` e `GROUP BY`.

SELECT 
	P.NOME AS NOME_PRODUTO,
	P.LINHA,
	SUM(IP.QUANTIDADE) AS QUANTIDADE_VENDIDA
	FROM TB_PRODUTOS AS P
INNER JOIN ITENSPEDIDO AS IP ON P.IDPRODUTO = IP.IDPRODUTO
GROUP BY P.NOME,P.LINHA
order by QUANTIDADE_VENDIDA DESC


-- Encontrar a regional com o maior valor total de vendas
-- Esta consulta junta `TB_REGIONAL`, `TB_CLIENTE` e `TB_PEDIDOS`,
-- soma o valor total de todos os pedidos por regional e ordena o resultado.
SELECT 
R.NOME AS REGIONAL,
SUM(P.VALORTOTAL) AS VALOR_VENDAS
FROM TB_REGIONAL AS R

INNER JOIN TB_CLIENTE AS C ON R.IDREGIONAL = C.IDREGIONAL
INNER JOIN TB_PEDIDOS AS P ON C.IDCLIENTE = P.IDCLIENTE
GROUP BY R.NOME
ORDER BY VALOR_VENDAS DESC


--Exemplo 5: Encontrar clientes que compraram um produto específico
-- Esta consulta usa múltiplos JOINs para rastrear quem comprou o 
--'Capacete de Ciclismo Pro'.
-- Ela une `TB_CLIENTE`, `TB_PEDIDOS`, `ITENSPEDIDO` e `TB_PRODUTOS`.

SELECT DISTINCT
   C.NOME AS CLIENTE,
   C.EMAIL_CLIENTE AS EMAIL

   FROM  TB_CLIENTE AS C
	JOIN TB_PEDIDOS AS P ON C.IDCLIENTE = P.IDCLIENTE
	JOIN ITENSPEDIDO AS IP ON P.IDPEDIDO = IP.IDPEDIDO
	JOIN TB_PRODUTOS AS PR ON IP.IDPRODUTO = PR.IDPRODUTO
   WHERE PR.NOME = 'Capacete de Ciclismo Pro'

