1--- CONSULTAS FUNCIONARIOS DO DEPARTAMENTO(TB EMPREGADO)
--DE CODIGO 2 QUE GANHAM SALARIO ACIMA DE 5000 REIAS







2)--CONSULTA FUNCIONAIOS DO DEPARTAMENTO DE CODIGO 2  OU(OR)
--AQUELES QUE GANHAM SALARIO ACIMA DE 5000





3)-- FUNCIONÁRIOS COM SALARIOS ENTRE 3000 E 5000 REIAS




4)-- CONSULTAS FUNCIONÁRIOS COM SALARIO ABAIXO DE 3000 OU
--ACIMA DE 5000




5)--FUNCIONARIOS ADMITIDOS ENTRE ANO 2000.1.1 E 2000.12.31





6)--- FUNCIONARIOS ADMITIDOS NO ANO 2000

