CREATE DATABASE BD_BYCICLON;
USE BD_BYCICLON
------------------------------------------------------------------
-- Crie a tabela: TB_ENDEREÇOS (PAIS, UF, CIDADE, BAIRRO, RUA, NUMERO)
CREATE TABLE TB_ENDERECOS(
IDENDERECO INT IDENTITY(1,1) NOT NULL,
PAIS VARCHAR(30) NOT NULL ,
UF CHAR(2) NOT NULL,
CIDADE VARCHAR (30) NOT NULL,
BAIRRO VARCHAR (30) NOT NULL,
RUA VARCHAR (50) NOT NULL,
NUMERO INT NOT NULL,
PRIMARY KEY (IDENDERECO)
);
------------------------------------------------------------------
-- Crie a tabela: TB_REGIONAL(idEndereco, Nome, DDD, Telefone)

CREATE TABLE  TB_REGIONAL (
IDREGIONAL INT IDENTITY(1,1) NOT NULL,
IDENDERECO INT NOT NULL,
NOME VARCHAR(50) NOT NULL,
DDD CHAR(2) NOT NULL,
TELEFONE CHAR(8) NOT NULL,
PRIMARY KEY (IDREGIONAL),
FOREIGN KEY (IDENDERECO) REFERENCES TB_ENDERECOS(IDENDERECO)
);
------------------------------------------------------------------
-- 1) Crie a tabela: TB_CLIENTE (IDENDERECO, IDREGIONAL, NOME, EMAIL, CPF)

CREATE TABLE TB_CLIENTE (
IDCLIENTE INT IDENTITY(1,1) NOT NULL,
IDENDERECO INT NOT NULL,
IDREGIONAL INT NOT NULL,
NOME VARCHAR(50) NOT NULL,
EMAIL VARCHAR(50) NOT NULL,
CPF CHAR(11) NOT NULL,
PRIMARY KEY (IDCLIENTE),
FOREIGN KEY (IDENDERECO) REFERENCES TB_ENDERECOS(IDENDERECO),
FOREIGN KEY (IDREGIONAL) REFERENCES TB_REGIONAL(IDREGIONAL)
);


-----------------------------------------------------------------
-- 2) Crie a tabela: TB_VENDEDORES -(IDENDERECO, IDREGIONAL, NOME, EMAIL, CPF)
CREATE TABLE TB_VENDEDORES(
IDVENDEDOR INT IDENTITY (1,1) NOT NULL,
IDENDERECO INT NOT NULL,
IDREGIONAL INT NOT NULL,
NOME VARCHAR(50) NOT NULL,
EMAIL VARCHAR (50) NOT NULL,
CPF CHAR(11) NOT NULL,
PRIMARY KEY (IDVENDEDOR),
FOREIGN KEY (IDENDERECO) REFERENCES TB_ENDERECOS(IDENDERECO),
FOREIGN KEY (IDREGIONAL) REFERENCES TB_REGIONAL(IDREGIONAL)
);

------------------------------------------------------------------
-- 3) Crie a tabela: TB_PRODUTOS - NOME, LINHA, VALORUNITARIO

CREATE TABLE TB_PRODUTOS (
IDPRODUTO INT IDENTITY(1,1) NOT NULL,
NOME VARCHAR (50) NOT NULL,
LINHA VARCHAR(100) NOT NULL,
VALORUNITARIO MONEY NOT NULL,
PRIMARY KEY (IDPRODUTO)
);

------------------------------------------------------------------
-- 4) Crie a tabela: TB_PEDIDOS -IDCLIENTE, IDVENDEDOR, DATAPEDIDO, QTDITENS, VALORTOTAL
CREATE TABLE TB_PEDIDOS(
IDPEDIDO INT IDENTITY (1,1) NOT NULL,
IDCLIENTE INT NOT NULL,
IDVENDEDOR INT NOT NULL,
DATAPEDIDO DATE NOT NULL,
QTDITENS INT NOT NULL,
VALORTOTAL MONEY NOT NULL,
PRIMARY KEY (IDPEDIDO),
FOREIGN KEY (IDCLIENTE) REFERENCES TB_CLIENTE(IDCLIENTE),
FOREIGN KEY (IDVENDEDOR) REFERENCES TB_VENDEDORES(IDVENDEDOR)
);

---------------------------------------------------------------
-- 5) Crie a tabela: TB_ITENS_PEDIDOS 
--idPedido, idProduto, quantidade, precoUnitario, desconto

CREATE TABLE ITENSPEDIDO (
IDITEM INT IDENTITY(1,1) NOT NULL,
IDPEDIDO INT NOT NULL,
IDPRODUTO INT NOT NULL,
QUANTIDADE INT NOT NULL,
PRECOUNITARIO MONEY NOT NULL,
DESCONTO MONEY NOT NULL,
PRIMARY KEY (IDITEM),
FOREIGN KEY (IDPEDIDO) REFERENCES TB_PEDIDOS(IDPEDIDO),
FOREIGN KEY (IDPRODUTO) REFERENCES TB_PRODUTOS(IDPRODUTO)
);
