--Formatar a data do pedido (TB_PEDIDOS.DATAPEDIDO) para 'dd/MM/yyyy' (SQLServer):


--Função Format(texto) - dd - dia com zero a esquerda ,MM , y
SELECT IDPEDIDO,
 FORMAT(DATAPEDIDO,'MMM') AS MÊSPEDIDO
  FROM TB_PEDIDOS

SELECT IDPEDIDO,
 FORMAT(DATAPEDIDO,'dddd') AS DIASEMANA 
  FROM TB_PEDIDOS


SELECT IDPEDIDO,
 FORMAT(DATAPEDIDO,'MMM/yyyy') AS MêsAno 
  FROM TB_PEDIDOS


--Exibir o nome do cliente em letras maiúsculas (SQL Server):
SELECT IDCLIENTE ,UPPER(NOME) AS NomeAjustado
	FROM TB_CLIENTE

--upper maiuscula / lower minuscula
SELECT IDCLIENTE ,lower(NOME) AS NomeAjustado
	FROM TB_CLIENTE
 

--ESQUERDA extrair os 3 digitos Á esquerda da coluna Nome (TB_PRODUTOS)
SELECT IDPRODUTO ,
  LEFT(NOME,3) AS NOME_CURTO FROM TB_PRODUTOS

SELECT IDPRODUTO ,
  RIGHT(NOME,3) AS NOME_CURTO FROM TB_PRODUTOS
 
--CONCATENAR Nome da Rua com o Número CONCAT

SELECT * FROM TB_ENDERECOS
SELECT IDENDERECO , CONCAT(RUA,',',NUMERO) AS
 'ENDEREÇO COMPLETO' FROM TB_ENDERECOS


-- Exibir a data do pedido com o nome do MÊs completo e o dia da semana abreviado
-- ' ddd , ddd,MMMM yyyy'

SELECT IDPEDIDO , 
  FORMAT(DATAPEDIDO,'dddd,dd MMMM yyyy') AS DATAPEDIDO
   FROM TB_PEDIDOS


--DIFERENÇA DE DIAS (DAY,YEAR, MONTH, WEEK ,HOUR,QUARTER)
--datediff
SELECT IDPEDIDO ,DATAPEDIDO,
  DATEDIFF(DAY,DATAPEDIDO,GETDATE()) AS DIASPEDIDO
   FROM TB_PEDIDOS

SELECT IDPEDIDO ,DATAPEDIDO,
  DATEDIFF(MONTH,DATAPEDIDO,GETDATE()) AS DIASPEDIDO
   FROM TB_PEDIDOS


--Adicionar / subtrair intervalos
---DATEADD

SELECT IDPEDIDO,DATAPEDIDO,
	DATEADD(day,7,DATAPEDIDO) AS Mais7dias,
		DATEADD(MONTH,-3,DATAPEDIDO) AS MENOS3mESES,
			DATEADD(YEAR,1,DATAPEDIDO) AS ANO
from TB_PEDIDOS


--Clientes que farão aniversário hoje
SELECT * FROM  TB_CLIENTE
---------------------------------------------------------

SELECT IDPEDIDO,DATAPEDIDO
 FROM TB_PEDIDOS

 WHERE MONTH(DATAPEDIDO) = MONTH(GETDATE())
 AND WEEKDAY(DATAPEDIDO) = WEEKDAY(GETDATE())
 

--- Último dia do mês(MÊS ATUAL) FIMMÊS (EOMONTH)
SELECT EOMONTH (DATAPEDIDO,-2)
 FROM TB_PEDIDOS

 SELECT EOMONTH (DATAPEDIDO,0)
 FROM TB_PEDIDOS
 

--- Último dia do mês(MÊS SEGUINTE)

