--Exemplos de ALTER TABLE com Base na Carga de Dados:



-- Percebemos que o campo EMAIL na tabela TB_VENDEDORES é muito curto para alguns e-mails.

ALTER TABLE TB_VENDEDORES
ALTER COLUMN EMAIL VARCHAR(100) NOT NULL
-- ALTERAR NA COLUNA NOME DA TABELA REGIONAL PARA TAMANHO 80
--NOT NULL

ALTER TABLE TB_REGIONAL
ALTER COLUMN NOME VARCHAR(80) NOT NULL

--Renomear uma Coluna da Tabela
EXEC sp_rename 
  'TB_CLIENTE.EMAIL'  , 'EMAIL_CLIENTE' ,'COLUMN'

--RENOMEAR UMA TABELA

EXEC SP_RENAME 'TB_ENDERECOS','TB_ENDERECO'
