--Exemplos de ALTER TABLE com Base na Carga de Dados:



-- Percebemos que o campo EMAIL na tabela TB_VENDEDORES é muito curto para alguns e-mails.

ALTER TABLE TB_VENDEDORES
ALTER COLUMN EMAIL VARCHAR(100) NOT NULL


--Excluir uma chave Primaria
--Primeiro, remover FK (ex: de TB_PEDIDOS para TB_CLIENTE)
ALTER TABLE TB_PEDIDOS
DROP CONSTRAINT FK_TB_PEDIDOS_CLIENTE

-- Agora sim, remover a chave primária da TB_CLIENTE
ALTER TABLE TB_CLIENTE
DROP CONSTRAINT PK_TBCLIENTE

--Adicionando a Chave Primaria da Tb_cliente
ALTER TABLE TB_CLIENTE
 ADD CONSTRAINT PK_TBCLIENTE PRIMARY KEY(IDCLIENTE)

---Adicionando o Relaconamento de Cliente com Pedidos
ALTER TABLE TB_PEDIDOS
ADD CONSTRAINT FK_TB_PEDIDOS_CLIENTE FOREIGN KEY (IDCLIENTE)
REFERENCES TB_CLIENTE(IDCLIENTE)


-- ALTERAR NA COLUNA NOME DA TABELA REGIONAL PARA TAMANHO 80
--NOT NULL

ALTER TABLE TB_REGIONAL
ALTER COLUMN NOME VARCHAR(80) NOT NULL

--Renomear uma Coluna da Tabela
EXEC sp_rename 
  'TB_CLIENTE.EMAIL'  , 'EMAIL_CLIENTE' ,'COLUMN'

--RENOMEAR UMA TABELA

EXEC SP_RENAME 'TB_ENDERECOS','TB_ENDERECO'
