---select case---

/*categoria
valorunitario < 1000 'economia'
valor unitario entre 1000 e 2000 'MÉDIO'
caso contrario premium
*/
SELECT NOME,LINHA,VALORUNITARIO,
  CASE
    WHEN VALORUNITARIO < 1000 THEN 'ECONOMIA'
	WHEN VALORUNITARIO BETWEEN 1000 AND 2000 THEN 'MÉDIO'
 
  ELSE 'PREMIUM'
  END
  AS CATEGORIA 
   FROM TB_PRODUTOS
--------------------------------------------------------------

---IDCLIENTE,IDVENDEDOR,DATAPEDIDO QTDITENS VALORTOTAL

/* CASO VALOR TOTAL < 1000 ENTAO 'BAIXO'
CASO VALOR TOTAL ESTEJA ENTRE 1000 E 2000 �MEDIO
CASO CONTRARIO 'ALTO'
--NOME DA COLUNA -- CLASSIFICAÇÃO
DA TABELA TB_PEDIDOS---
*/

SELECT 
IDCLIENTE,
IDVENDEDOR,
DATAPEDIDO,
QTDITENS,
VALORTOTAL,

CASE 
  WHEN VALORTOTAL < 1000 THEN 'BAIXO'
  WHEN VALORTOTAL BETWEEN 100 AND 2000 THEN 'MÉDIO'
ELSE 'ALTO'
END
   AS CLASSIFICAÇÃO
   FROM TB_PEDIDOS






--Usando TB_PRODUTOS – simulação de política de preço mínima por categoria

SELECT * FROM TB_PRODUTOS

SELECT 
 IDPRODUTO,
 NOME,
 LINHA,
 VALORUNITARIO,

 CASE 
	WHEN LINHA = 'BICICLETAS' AND VALORUNITARIO < 1000 THEN 'PREÇO MINIMO'
	WHEN LINHA = 'Acess?rios' AND VALORUNITARIO < 50 THEN 'PREÇO ABAIXO DO MINIMO'
	WHEN LINHA = 'Manuten??o' AND VALORUNITARIO < 70 THEN ' PREÇO RAZOÁVEL'
  
 ELSE 'PREÇO OK'
 END AS AVALIAÇÃO_PREÇO

 FROM TB_PRODUTOS


--Determinar se o pedido teve múltiplos itens(TABELA PEDIDOS) COLUNA QTDITENS

--- SE A QUANTIDADE DE ITENS FOR MAIOR QUE 1 'PEDIDOS COM VARIOS ITENS'
--SENAO PEDIDO SIMPLES

SELECT 
 IDPEDIDO,
 QTDITENS,
  CASE
	WHEN QTDITENS > 1 THEN 'PEDIDO COM VARIOS ITENS'
    ELSE 'PEDIDO SIMPLES'
  END AS TIPO_PEDIDO
  FROM TB_PEDIDOS
 





--Classificar os pedidos como "antigos", "recentes" ou "futuros" (TB_PEDIDOS) COLUNA DATAPEDIDO

-- SE DATAPEDIDO FOR MENOR QUE '2025-01-0-1 ENTAO 'ANTIGO'
--- SE DATAPEDIDO ESTIVER ENTRE A DATA '2025-01-01' E DATA ATUAL ENTAO É 'RECENTE'
-- SENÃO FUTURO

SELECT 
IDPEDIDO,
DATAPEDIDO,
  
  CASE
		WHEN DATAPEDIDO < '2025-01-01' THEN 'ANTIGO'
		WHEN DATAPEDIDO BETWEEN '2025-01-01' AND GETDATE() THEN 'RECENTE'

  ELSE 'FUTURO'

  END AS STATUS_PEDIDO
  FROM TB_PEDIDOS

